# This file is automatically generated by tools/generate_config_typing.py
# Do not modify this file directly.
# The content of this file is based on the config-definition.yaml file.
# It is used to provide type hints for the config module, to be used by your IDE.

# fmt: off

import disnake

from starbot.configuration.config_abc import ConfigABC

class GuildConfig(ConfigABC):

    class bot(ConfigABC):
        description: str

    class phishing(ConfigABC):
        should_filter: bool
        action: str
        dm: str
        bypass_permission: disnake.Permissions

    class logging(ConfigABC):

        class channels(ConfigABC):
            default: int
            messages: int
            users: int

        class log(ConfigABC):
            joins: bool
            messages: bool
            server: bool
            members: bool

    class config(ConfigABC):

        class perms(ConfigABC):
            role: int
            discord: disnake.Permissions

    class colors(ConfigABC):
        danger: int
        warning: int
        info: int
        success: int
