bot:
  info_channel:
    type: optional:discord_channel
    default: null
    description: "Bot: Channel where important updates will be posted."
  description:
    type: str
    default: |
      ${display_name} is a general purpose bot aiming to provide the essential functionalities needed to run your community, while being an open-source alternative to larger bots.
    description: "Bot: The description of the bot"

logging:
  channels:
    default:
      type: optional:discord_channel
      default: null
      description: "Logging: Channel where all the logs will be sent, unless a specific channel is set"
    moderation:
      type: optional:discord_channel
      default: REF logging.channels.default
      description: "Logging: Channel where moderation actions will be logged"
    messages:
      type: optional:discord_channel
      default: REF logging.channels.default
      description: "Logging: Channel where to log message edits and deletions"
    members:
      type: optional:discord_channel
      default: REF logging.channels.default
      description: "Logging: Channel where to log updates done to the members"
    joins:
      type: optional:discord_channel
      default: REF logging.channels.default
      description: "Logging: Channel where to log when members join or leave the server"
    server:
      type: optional:discord_channel
      default: REF logging.channels.default
      description: "Logging: Channel where to log when the server is updated"

moderation:
  perms:
    role:
      type: optional:discord_role
      default: null
      description: "Moderation: Role required to use the moderation commands"
    discord:
      type: optional:discord_permission
      default: ban_members
      description: "Moderation: Discord permission required to use the moderation commands"
  messages:
    dm_description:
      type: optional:str
      default: null
      description: "Moderation: Embed message sent to the user. Can link to the rules or how to appeal, for example."

config:
  perms:
    role:
      type: optional:discord_role
      default: null
      description: "Config: Role required to change the configuration"
    discord:
      type: optional:discord_permission
      default: administrator
      description: "Config: Discord permission required to change the configuration"

phishing:
  should_filter:
    type: bool
    default: true
    description: "Phishing: Whether to filter out phishing links"
  action:
    type: choice
    choices:
      - kick
      - ban
      - ignore
    default: kick
    description: "Phishing: What action to perform when a domain is detected"
  dm:
    type: str
    default: |
      Hi ${user}. Your account has been used to send links to a phishing website. ${action}
      If you are not aware of sending them, that means your account has been compromised.

      Here is a guide from Discord on how to change your password: ${LINK_PASSWORD}.

      We also highly recommend that you enable 2-factor authentication on your account, for heightened security: ${LINK_2FA}.
    description: "Phishing: The message to send to the user when a phishing link is detected"
  bypass_permission:
    type: discord_permission
    default: manage_messages
    description: "Phishing: The permission required to bypass the filter"

colors:
  danger:
    type: int
    default: "0xED4245"
    description: "Color: danger level"
  warning:
    type: int
    default: "0xFEE75C"
    description: "Color: warning level"
  info:
    type: int
    default: "0x5865F2"
    description: "Color: info level"
  success:
    type: int
    default: "0x57F287"
    description: "Color: success level"
