bot:
  description:
    type: str
    default: |
      ${display_name} is a general purpose bot aiming to provide the essential functionalities needed to run your community, while being an open-source alternative to larger bots.
    description: "Bot: The description of the bot"

phishing:
  should_filter:
    type: bool
    default: "true"
    description: "Phishing: Whether to filter out phishing links"
  action:
    type: choice
    choices:
      - kick
      - ban
      - ignore
    default: kick
    description: "Phishing: What action to perform when a domain is detected"
  dm:
    type: str
    default: |
      Hi ${user}. Your account has been used to send links to a phishing website. ${action}
      If you are not aware of sending them, that means your account has been compromised.

      Here is a guide from Discord on how to change your password: ${LINK_PASSWORD}.

      We also highly recommend that you enable 2-factor authentication on your account, for heightened security: ${LINK_2FA}.
    description: "Phishing: The message to send to the user when a phishing link is detected"
  bypass_permission:
    type: discord_permission
    default: manage_messages
    description: "Phishing: The permission required to bypass the filter"

logging:
  channels:
    default:
      type: discord_channel
      default: null
      description: "Logging: The default channel to log to"
    messages:
      type: discord_channel
      default: null
      description: "Logging: The channel to log messages to"
    user:
      type: discord_channel
      default: REF logging.default_channel
      description: "Logging: The channel to log user actions to"
  log:
    joins:
      type: bool
      default: "true"
      description: "Logging: Whether to log when a user joins or leaves"
    messages:
      type: bool
      default: "true"
      description: "Logging: Whether to log when a message is edited or deleted"
    server:
      type: bool
      default: "true"
      description: "Logging: Whether to log when changes are made to the server"
    members:
      type: bool
      default: "true"
      description: "Logging: Whether to log when members are modified"

config:
  perms:
    discord_role:
      type: discord_role
      default: null
      description: "Config: discord_role required to change the configuration"
    discord:
      type: discord_permission
      default: administrator
      description: "Config: Discord permission required to change the configuration"

colors:
  danger:
    type: int
    default: "0xED4245"
    description: "Color: danger level"
  warning:
    type: int
    default: "0xFEE75C"
    description: "Color: warning level"
  info:
    type: int
    default: "0x5865F2"
    description: "Color: info level"
  success:
    type: int
    default: "0x57F287"
    description: "Color: success level"
