# This file is automatically generated by tools/generate_config_typing.py
# Do not modify this file directly.
# The content of this file is based on the config-definition.yaml file.
# It is used to provide type hints for the config module, to be used by your IDE.

# fmt: off
from starbot.configuration.config_abc import ConfigABC

class GuildConfig(ConfigABC):

    class config(ConfigABC):

        class perms(ConfigABC):
            role: int
            discord: str

    class colors(ConfigABC):
        danger: int
        warning: int
        info: int
        success: int
