"""Add guild and config entries

Revision ID: 07d507061c59
Revises:
Create Date: 2022-01-27 16:01:40.067484

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "07d507061c59"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guild",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("discord_id", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("discord_id"),
    )
    op.create_table(
        "config_entry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guild_id", sa.Integer(), nullable=True),
        sa.Column("key", sa.String(length=255), nullable=True),
        sa.Column("value", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["guild.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("config_entry")
    op.drop_table("guild")
    # ### end Alembic commands ###
