"""empty message

Revision ID: fd5b445b8fd3
Revises: 0f088a1a0f2d
Create Date: 2022-03-22 08:08:51.136974

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fd5b445b8fd3"
down_revision = "0f088a1a0f2d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "role_picker",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=True),
        sa.Column("message_id", sa.BigInteger(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["guild.guild_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "role_picker_entry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("picker_id", sa.BigInteger(), nullable=False),
        sa.Column("role_id", sa.BigInteger(), nullable=True),
        sa.Column("message", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["picker_id"],
            ["role_picker.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("role_picker_entry")
    op.drop_table("role_picker")
    # ### end Alembic commands ###
